COLUMNS:
  id: int64
  carat: float64
  cut: object
  color: object
  clarity: object
  depth: float64
  table: float64
  x: float64
  y: float64
  z: float64
  price: int64

TARGET_COLUMN:
  name: price
